LatoCruiser/Models/BookingRequest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LatoCruiser.Models
{
    public class BookingRequest
    {   
        [Key]
        public int Id { get; set; }
        public string BookerName { get; set; }
        public string BookerEmail { get; set; }
        public string BookerPhone { get; set; }
        public DateTime BookStart { get; set; }
        public DateTime BookEnd { get; set; }
        public string BookDescription { get; set; }
    }
}

LatoCruiser/Models/ErrorViewModel.cs
using System;

namespace LatoCruiser.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LatoCruiser/Controllers/BookingRequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LatoCruiser.Data;
using LatoCruiser.Models;

using Syncfusion.EJ2.Grids;


namespace LatoCruiser.Controllers
{
    public class BookingRequestsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BookingRequestsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: BookingRequests
        public async Task<IActionResult> Index()
        {

            
            List<object> DataRange = new();
            DataRange.Add(new { Text = "1,000 Rows 11 Columns", Value = "1000" });
            DataRange.Add(new { Text = "10,000 Rows 11 Columns", Value = "10000" });
            DataRange.Add(new { Text = "1,00,000 Rows 11 Columns", Value = "100000" });
            ViewBag.Data = DataRange;

            var Order = await _context.Booking.ToListAsync();
            ViewBag.DataSource = Order;


            return View(await _context.Booking.ToListAsync());
        }

        // GET: BookingRequests/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookingRequest = await _context.Booking
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bookingRequest == null)
            {
                return NotFound();
            }

            return View(bookingRequest);
        }

        // GET: BookingRequests/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BookingRequests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,BookerName,BookerEmail,BookerPhone,BookStart,BookEnd,BookDescription")] BookingRequest bookingRequest)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bookingRequest);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            return View(bookingRequest);
        }

        // GET: BookingRequests/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookingRequest = await _context.Booking.FindAsync(id);
            if (bookingRequest == null)
            {
                return NotFound();
            }
            return View(bookingRequest);
        }

        // POST: BookingRequests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BookerName,BookerEmail,BookerPhone,BookStart,BookEnd,BookDescription")] BookingRequest bookingRequest)
        {
            if (id != bookingRequest.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bookingRequest);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingRequestExists(bookingRequest.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bookingRequest);
        }

        // GET: BookingRequests/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bookingRequest = await _context.Booking
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bookingRequest == null)
            {
                return NotFound();
            }

            return View(bookingRequest);
        }

        // POST: BookingRequests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bookingRequest = await _context.Booking.FindAsync(id);
            _context.Booking.Remove(bookingRequest);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookingRequestExists(int id)
        {
            return _context.Booking.Any(e => e.Id == id);
        }
    }
}

LatoCruiser/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using LatoCruiser.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace LatoCruiser.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LatoCruiser/Views/BookingRequests/Create.cshtml
@model LatoCruiser.Models.BookingRequest
@using Syncfusion.EJ2


@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BookingRequest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BookerName" class="control-label"></label>
                <input asp-for="BookerName" class="form-control" />
                <span asp-validation-for="BookerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookerEmail" class="control-label"></label>
                <input asp-for="BookerEmail" class="form-control" />
                <span asp-validation-for="BookerEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookerPhone" class="control-label"></label>
                <input asp-for="BookerPhone" class="form-control" />
                <span asp-validation-for="BookerPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookStart" class="control-label"></label>
                <ejs-datepicker id="datepicker" ejs-for="BookStart" format="dd-MM-yyyy" placeholder="Choose a Date"></ejs-datepicker>
                <span asp-validation-for="BookStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookEnd" class="control-label"></label>
                <ejs-datepicker id="datepicker2" ejs-for="BookEnd" format="dd-MM-yyyy" placeholder="Choose a Date"></ejs-datepicker>
                <span asp-validation-for="BookEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookDescription" class="control-label"></label>
                <input asp-for="BookDescription" class="form-control" />
                <span asp-validation-for="BookDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LatoCruiser/Views/BookingRequests/Delete.cshtml
@model LatoCruiser.Models.BookingRequest

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BookingRequest</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookerEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookerEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookerPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookerPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookStart)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookStart)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookEnd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookEnd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookDescription)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

LatoCruiser/Views/BookingRequests/Details.cshtml
@model LatoCruiser.Models.BookingRequest

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>BookingRequest</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookerEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookerEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookerPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookerPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookStart)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookStart)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookEnd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookEnd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookDescription)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

LatoCruiser/Views/BookingRequests/Edit.cshtml
@model LatoCruiser.Models.BookingRequest

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BookingRequest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="BookerName" class="control-label"></label>
                <input asp-for="BookerName" class="form-control" />
                <span asp-validation-for="BookerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookerEmail" class="control-label"></label>
                <input asp-for="BookerEmail" class="form-control" />
                <span asp-validation-for="BookerEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookerPhone" class="control-label"></label>
                <input asp-for="BookerPhone" class="form-control" />
                <span asp-validation-for="BookerPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookStart" class="control-label"></label>
                <input asp-for="BookStart" class="form-control" />
                <span asp-validation-for="BookStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookEnd" class="control-label"></label>
                <input asp-for="BookEnd" class="form-control" />
                <span asp-validation-for="BookEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookDescription" class="control-label"></label>
                <input asp-for="BookDescription" class="form-control" />
                <span asp-validation-for="BookDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LatoCruiser/Views/BookingRequests/Index.cshtml
@model IEnumerable<LatoCruiser.Models.BookingRequest>
@using Syncfusion.EJ2

@{
    ViewData["Title"] = "Index";
}
@{

    List<object> commands = new List<object>();
    commands.Add(new { type = "Edit", buttonOption = new { iconCss = "e-icons e-edit", cssClass = "e-flat" } });
    commands.Add(new { type = "Delete", buttonOption = new { iconCss = "e-icons e-delete", cssClass = "e-flat" } });
    commands.Add(new { type = "Save", buttonOption = new { iconCss = "e-icons e-update", cssClass = "e-flat" } });
    commands.Add(new { type = "Cancel", buttonOption = new { iconCss = "e-icons e-cancel-icon", cssClass = "e-flat" } });

}
<p>
    <a asp-action="Create">Create New</a>
</p>
<ejs-grid id="Grid"
          dataSource="@ViewBag.DataSource"
          height="273"
          toolbar="@(new List<string>() { "Add", "Edit", "Delete", "Cancel", "Update" })"
          allowPaging="true" allowSorting="true">

    <e-grid-editSettings allowAdding="true" allowDeleting="true" allowEditing="true"></e-grid-editSettings>
    <e-grid-pagesettings pageSize="10"></e-grid-pagesettings>



    <e-grid-columns>
        <e-grid-column field="@Html.DisplayNameFor(model => model.BookerName)" headerText="Booker" textAlign="Left" width="120"></e-grid-column>
        <e-grid-column field="@Html.DisplayNameFor(model => model.BookerEmail)" headerText="Email" width="130"></e-grid-column>
        <e-grid-column field="@Html.DisplayNameFor(model => model.BookerPhone)" headerText="Phone" width="130" textAlign="Right" format="yMd"></e-grid-column>
        <e-grid-column field="@Html.DisplayNameFor(model => model.BookStart)" headerText="Date Start" customFormat="@(new { type ="date", format="dd/MM/yyyy" })" width="120"></e-grid-column>
        <e-grid-column field="@Html.DisplayNameFor(model => model.BookEnd)" headerText="Date End" customFormat="@(new { type ="date", format="dd/MM/yyyy" })" width="120"></e-grid-column>
        <e-grid-column field="@Html.DisplayNameFor(model => model.BookDescription)" headerText="Notes" width="120"></e-grid-column>
        <e-grid-column headerText="Manage Records" width="150" commands="commands"></e-grid-column>
    </e-grid-columns>
</ejs-grid>


<h1>Index</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BookerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookerEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookerPhone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookStart)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookEnd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookDescription)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BookerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BookerEmail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BookerPhone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BookStart)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BookEnd)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BookDescription)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

LatoCruiser/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <div>
        <ejs-calendar id="calendar"></ejs-calendar>
    </div>
</div>

LatoCruiser/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LatoCruiser</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @* Syncfusion Essential JS 2 Styles *@
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />

    @* Syncfusion Essential JS 2 Scripts *@
    <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LatoCruiser</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BookingRequests" asp-action="Index">Bookings</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - LatoCruiser - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <ejs-scripts></ejs-scripts>
</body>
</html>